language: ruby
install: bundle install
rvm:
  - 2.4.2
env:
  - DATABASE_URL=postgres://postgres@localhost/postgres
before_script:
  - bundle exec rake db:enable_postgis
cache: bundler
services:
  - elasticsearch
  - postgresql
  - redis-server
